# Generated by Django 6.0.3 on 2026-03-10 11:28

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=core.models.task_icon_upload_path,
                    ),
                ),
                ("default_amount", models.PositiveIntegerField(default=1)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("none", "Нет"),
                            ("day", "День"),
                            ("week", "Неделя"),
                            ("month", "Месяц"),
                            ("year", "Год"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("none", "Нет"),
                            ("floating", "В течение периода"),
                            ("fixed", "Не раньше даты"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                (
                    "fixed_weekday",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "fixed_day_of_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "fixed_month_of_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Январь"),
                            (2, "Февраль"),
                            (3, "Март"),
                            (4, "Апрель"),
                            (5, "Май"),
                            (6, "Июнь"),
                            (7, "Июль"),
                            (8, "Август"),
                            (9, "Сентябрь"),
                            (10, "Октябрь"),
                            (11, "Ноябрь"),
                            (12, "Декабрь"),
                        ],
                        null=True,
                    ),
                ),
                ("next_available_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("selected_count", models.PositiveIntegerField(default=0)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("selected_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        related_name="group_templates", to="core.tasktemplate"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlockTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_title", models.CharField(max_length=128)),
                ("template_icon", models.CharField(blank=True, max_length=255)),
                ("position", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
                ("amount", models.PositiveIntegerField(default=1)),
                ("time", models.FloatField(default=1)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="core.block",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tasktemplate",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tasktemplate",
            index=models.Index(
                fields=["owner", "next_available_at"],
                name="core_taskte_owner_i_06f662_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tasktemplate",
            index=models.Index(
                fields=["owner", "priority"], name="core_taskte_owner_i_78ccc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tasktemplate",
            index=models.Index(
                fields=["owner", "selected_count"],
                name="core_taskte_owner_i_42f20a_idx",
            ),
        ),
    ]
