# Generated by Django 6.0.3 on 2026-03-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="is_hided",
            field=models.BooleanField(default=False),
        ),
    ]
