# Generated by Django 6.0.3 on 2026-03-11 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_block_is_hided"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemTaskTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=255)),
                ("default_amount", models.PositiveIntegerField(default=1)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("none", "Нет"),
                            ("day", "День"),
                            ("week", "Неделя"),
                            ("month", "Месяц"),
                            ("year", "Год"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("none", "Нет"),
                            ("floating", "В течение периода"),
                            ("fixed", "Не раньше даты"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                (
                    "fixed_weekday",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "fixed_day_of_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "fixed_month_of_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Январь"),
                            (2, "Февраль"),
                            (3, "Март"),
                            (4, "Апрель"),
                            (5, "Май"),
                            (6, "Июнь"),
                            (7, "Июль"),
                            (8, "Август"),
                            (9, "Сентябрь"),
                            (10, "Октябрь"),
                            (11, "Ноябрь"),
                            (12, "Декабрь"),
                        ],
                        null=True,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="blocktask",
            options={"ordering": ["position"]},
        ),
        migrations.RenameField(
            model_name="blocktask",
            old_name="template_icon",
            new_name="icon",
        ),
        migrations.RenameField(
            model_name="blocktask",
            old_name="template_title",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="blocktask",
            name="template",
        ),
        migrations.AddField(
            model_name="blocktask",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blocktask",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="blocktask",
            index=models.Index(
                fields=["block", "position"], name="core_blockt_block_i_fb7d55_idx"
            ),
        ),
    ]
