# Generated by Django 6.0.3 on 2026-03-13 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_systemtasktemplate_alter_blocktask_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktemplate",
            name="system_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.systemtasktemplate",
            ),
        ),
    ]
