# Generated by Django 6.0.3 on 2026-03-13 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_tasktemplate_system_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tasktemplate",
            constraint=models.UniqueConstraint(
                fields=("owner", "system_template"), name="unique_user_system_template"
            ),
        ),
    ]
