# Generated by Django 6.0.3 on 2026-03-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_tasktemplate_unique_user_system_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocktask",
            name="is_encrypted",
            field=models.BooleanField(default=False),
        ),
    ]
