# Generated by Django 6.0.3 on 2026-03-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_blocktask_is_encrypted"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocktask",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
