# Generated by Django 6.0.3 on 2026-03-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_blocktask_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemtasktemplate",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tasktemplate",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
