# Generated by Django 6.0.3 on 2026-03-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_userpin"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpin",
            name="is_pin_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userpin",
            name="pin_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
