# Generated by Django 6.0.3 on 2026-03-18 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_userpin_is_pin_enabled_alter_userpin_pin_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocktask",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="block_tasks",
                to="core.tasktemplate",
            ),
        ),
    ]
