# Generated by Django 6.0.3 on 2026-03-18 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_blocktask_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocktask",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="block_tasks",
                to="core.tasktemplate",
            ),
        ),
    ]
