# Generated by Django 6.0.3 on 2026-03-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_blocktask_template"),
    ]

    operations = [
        migrations.RenameField(
            model_name="block",
            old_name="is_hided",
            new_name="is_hidden",
        ),
    ]
