# Generated by Django 6.0.3 on 2026-03-18 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_rename_is_hided_block_is_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocktask",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="block_tasks",
                to="core.tasktemplate",
            ),
        ),
    ]
