# Generated by Django 6.0.3 on 2026-04-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_blocktask_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="target_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
