# Generated by Django 6.0.3 on 2026-04-25 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_blockweather"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="grouptemplate",
            index=models.Index(
                fields=["owner", "-updated_at", "-id"],
                name="core_groupt_owner_i_55365d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="grouptemplate",
            index=models.Index(fields=["owner"], name="core_groupt_owner_i_84895e_idx"),
        ),
    ]
