# Generated by Django 6.0.3 on 2026-04-26 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_grouptemplate_core_groupt_owner_i_55365d_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obj_uuid", models.UUIDField(db_index=True)),
                (
                    "object_type",
                    models.CharField(
                        choices=[("block", "Block"), ("blocktask", "BlockTask")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                ("device_id", models.UUIDField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.UUIDField(db_index=True, unique=True)),
                (
                    "platform",
                    models.CharField(choices=[("android", "Android")], max_length=16),
                ),
                ("name", models.CharField(blank=True, max_length=128)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="block",
            name="uuid",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="blocktask",
            name="uuid",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(
                fields=["owner", "updated_at"], name="core_block_owner_i_f23d49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(
                fields=["owner", "uuid"], name="core_block_owner_i_c984bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blocktask",
            index=models.Index(fields=["uuid"], name="core_blockt_uuid_6189f1_idx"),
        ),
        migrations.AddField(
            model_name="deletedobject",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="deletedobject",
            index=models.Index(
                fields=["user", "deleted_at"], name="core_delete_user_id_95d202_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deletedobject",
            index=models.Index(
                fields=["obj_uuid", "object_type"],
                name="core_delete_obj_uui_a8f2ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["user", "last_sync_at"], name="core_device_user_id_689913_idx"
            ),
        ),
    ]
