# Generated by Django 6.0.3 on 2026-04-26 04:28
import uuid

from django.db import migrations


def fill_uuids(apps, schema_editor):
    Block = apps.get_model("core", "Block")
    BlockTask = apps.get_model("core", "BlockTask")

    for b in Block.objects.filter(uuid__isnull=True):
        b.uuid = uuid.uuid4()
        b.save(update_fields=["uuid"])

    for t in BlockTask.objects.filter(uuid__isnull=True):
        t.uuid = uuid.uuid4()
        t.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_deletedobject_device_block_uuid_blocktask_uuid_and_more"),
    ]

    operations = [
        migrations.RunPython(fill_uuids),
    ]
