# Generated by Django 6.0.3 on 2026-04-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_block_uuid_alter_blocktask_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouptemplate",
            name="uuid",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="systemtasktemplate",
            name="uuid",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="tasktemplate",
            name="uuid",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
