# Generated by Django 6.0.3 on 2026-04-26 21:42

from django.db import migrations
import uuid


def fill_uuid(apps, schema_editor):
    SystemTaskTemplate = apps.get_model("core", "SystemTaskTemplate")
    TaskTemplate = apps.get_model("core", "TaskTemplate")
    GroupTemplate = apps.get_model("core", "GroupTemplate")

    for obj in SystemTaskTemplate.objects.filter(uuid__isnull=True):
        obj.uuid = uuid.uuid4()
        obj.save(update_fields=["uuid"])

    for obj in TaskTemplate.objects.filter(uuid__isnull=True):
        obj.uuid = uuid.uuid4()
        obj.save(update_fields=["uuid"])

    for obj in GroupTemplate.objects.filter(uuid__isnull=True):
        obj.uuid = uuid.uuid4()
        obj.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_grouptemplate_uuid_systemtasktemplate_uuid_and_more"),
    ]

    operations = [migrations.RunPython(fill_uuid)]
