# Generated by Django 6.0.3 on 2026-04-26 21:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_auto_20260427_0042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouptemplate",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="systemtasktemplate",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="tasktemplate",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
