# Generated by Django 6.0.3 on 2026-04-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_grouptemplate_uuid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deletedobject",
            old_name="device_id",
            new_name="device_uuid",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="device_id",
            new_name="device_uuid",
        ),
    ]
