# Generated by Django 6.0.3 on 2026-04-30 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_rename_device_id_deletedobject_device_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocktask",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="block_tasks",
                to="core.block",
            ),
        ),
    ]
