# Generated by Django 6.0.3 on 2026-04-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_blocktask_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocktask",
            name="time",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
