# Generated by Django 6.0.3 on 2026-04-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_blocktask_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouptemplate",
            name="tasks",
            field=models.ManyToManyField(
                related_name="task_templates", to="core.tasktemplate"
            ),
        ),
    ]
