# Generated by Django 6.0.3 on 2026-05-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_grouptemplate_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktemplate",
            name="time",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
