# Generated by Django 6.0.3 on 2026-05-01 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_tasktemplate_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasktemplate",
            old_name="default_amount",
            new_name="amount",
        ),
    ]
