# Generated by Django 6.0.3 on 2026-05-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_rename_default_amount_tasktemplate_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="systemtasktemplate",
            old_name="default_amount",
            new_name="amount",
        ),
        migrations.AlterField(
            model_name="tasktemplate",
            name="time",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
