# Generated by Django 6.0.3 on 2026-05-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_rename_default_amount_systemtasktemplate_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemtasktemplate",
            name="time",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
