# Generated by Django 6.0.3 on 2026-05-09 18:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
