# Generated by Django 6.0.3 on 2026-05-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_systemtasktemplate_period_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasktemplate",
            name="period_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "Нет"),
                    ("day", "День"),
                    ("week", "Неделя"),
                    ("month", "Месяц"),
                    ("year", "Год"),
                ],
                default="none",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tasktemplate",
            name="schedule_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "Нет"),
                    ("floating", "В течение периода"),
                    ("fixed", "Не раньше даты"),
                ],
                default="none",
                max_length=16,
                null=True,
            ),
        ),
    ]
